version: '3'

services:
  app:
    image: prism:latest
    restart: always
    container_name: prism-srv
    environment:
      - MONGO_ENDPOINT="mongodb://mongo:27017/expressmongo"
      - API_PORT=3000
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - backend

  mongo:
    restart: always
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
    networks:
      - backend
    
networks:
  backend:

volumes:
  db-volume: